- name: Remove directory on all nodes
  hosts: mmai_mysql_database
  become: yes
  tasks:
    - name: Ensure directory is removed
      file:
        path: /mnt/disks/mmai-mysql-billing
        state: absent
